name: Deployment
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
       
    steps:
     - uses: actions/checkout@v1
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: Build static site
       run: npm install && npm run build && pwd && ls -ltrh
       # Share artifact inside workflow
     - name: Share artifact inside workflow
       uses: actions/upload-artifact@v1
       with:
         name: react-github-actions-build
         path: build
       # Download previously shared build
     - name: Get artifact
       uses: actions/download-artifact@v1
       with:
         name: react-github-actions-build
         path: $(pwd)
         #path: /home/runner/work/react-redux-realworld-example-app/react-redux-realworld-example-app/react-github-actions-build
         run: pwd && ls -altrh
         #     - uses: actions/checkout@v1
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # secrets
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
     - name: Deploy static site to S3 bucket
       run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }}/ --acl=public-read --delete --exclude '.git/*'
       working-directory: react-github-actions-build
     - name: Clear CloudFront CDN Distribution
       run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths /\*
